[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Goal,
    [ValidateSet('auto','raster-image','presentation','editable-diagram','architecture-diagram','scientific-figure','reference-image-reverse-design','content-card-series','content-infographic','content-cover','article-illustration','content-svg-diagram','content-slide-deck','visual-asset')][string]$Route = 'auto',
    [string]$OutputRoot,
    [switch]$Json
)
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..\..\..')).Path
if (-not $OutputRoot) { $OutputRoot = Join-Path $root '.runtime\work\visual-design-agent' }
function Resolve-VisualRoute([string]$text, [string]$requested) {
    if ($requested -ne 'auto') { return $requested }
    $lower = $text.ToLowerInvariant()
    if ($lower -match 'xhs|xiaohongshu|social card|\u5c0f\u7ea2\u4e66|\u56fe\u7247\u5361\u7247') { return 'content-card-series' }
    if ($lower -match 'infographic|\u4fe1\u606f\u56fe') { return 'content-infographic' }
    if ($lower -match 'cover image|article cover|\u6587\u7ae0\u5c01\u9762') { return 'content-cover' }
    if ($lower -match 'article illustration|illustrate( this)? article|\u6587\u7ae0\u914d\u56fe') { return 'article-illustration' }
    if ($lower -match 'svg diagram|content diagram|\u5185\u5bb9\u56fe\u8868') { return 'content-svg-diagram' }
    if ($lower -match 'content slide|content deck|\u5185\u5bb9\u5e7b\u706f') { return 'content-slide-deck' }
    if ($lower -match 'reference image|example image|reference visual|example visual|\u53c2\u8003\u56fe|\u4f8b\u56fe') { return 'reference-image-reverse-design' }
    if ($lower -match 'ppt|powerpoint|slide|\u6f14\u793a|\u7b54\u8fa9|\u5e7b\u706f') { return 'presentation' }
    if ($lower -match 'scientific figure|scientific illustration|graphical abstract|publication figure|\u79d1\u7814|\u673a\u5236\u56fe|\u56fe\u5f62\u6458\u8981') { return 'scientific-figure' }
    if ($lower -match 'architecture|workflow|uml|erd|bpmn|c4|network|drawio|\u67b6\u6784\u56fe|\u6d41\u7a0b\u56fe|\u65f6\u5e8f\u56fe|\u7f51\u7edc\u56fe') { return 'architecture-diagram' }
    if ($lower -match 'diagram|flowchart|\u56fe\u8868|\u5173\u7cfb\u56fe|\u793a\u610f\u56fe') { return 'editable-diagram' }
    if ($lower -match 'image|illustration|infographic|cover|\u6d77\u62a5|\u63d2\u56fe|\u5c01\u9762|\u4fe1\u606f\u56fe') { return 'raster-image' }
    return 'visual-asset'
}
$selectedRoute = Resolve-VisualRoute $Goal $Route
$routeOwners = @{ 'raster-image'=@('codex-image-workflow'); presentation=@('codex-office-cli','codex-image-workflow'); 'editable-diagram'=@('codex-image-workflow'); 'architecture-diagram'=@('codex-image-workflow'); 'scientific-figure'=@('codex-image-workflow','codex-office-cli'); 'reference-image-reverse-design'=@('codex-image-workflow','codex-office-cli'); 'content-card-series'=@('codex-image-workflow'); 'content-infographic'=@('codex-image-workflow'); 'content-cover'=@('codex-image-workflow'); 'article-illustration'=@('codex-image-workflow'); 'content-svg-diagram'=@('codex-image-workflow'); 'content-slide-deck'=@('codex-office-cli','codex-image-workflow'); 'visual-asset'=@('codex-image-workflow') }
$routeReferences = @{ 'raster-image'=@('skills/codex-image-workflow/SKILL.md','skills/codex-image-workflow/subskills/visual-format-selection/SKILL.md'); presentation=@('skills/codex-office-cli/subskills/ppt-deck-factory/SKILL.md'); 'editable-diagram'=@('skills/codex-image-workflow/subskills/drawio-skill/SKILL.md'); 'architecture-diagram'=@('skills/codex-image-workflow/subskills/drawio-skill/SKILL.md'); 'scientific-figure'=@('skills/codex-image-workflow/subskills/figure-optimization/SKILL.md','skills/codex-image-workflow/subskills/scientific-illustrator/SKILL.md'); 'reference-image-reverse-design'=@('skills/codex-image-workflow/subskills/visual-design-agent/SKILL.md','skills/codex-image-workflow/subskills/drawio-skill/SKILL.md','skills/codex-office-cli/subskills/ppt-deck-factory/SKILL.md'); 'content-card-series'=@('skills/codex-image-workflow/subskills/visual-design-agent/references/baoyu-content-design-routing.md'); 'content-infographic'=@('skills/codex-image-workflow/subskills/visual-design-agent/references/baoyu-content-design-routing.md'); 'content-cover'=@('skills/codex-image-workflow/subskills/visual-design-agent/references/baoyu-content-design-routing.md'); 'article-illustration'=@('skills/codex-image-workflow/subskills/visual-design-agent/references/baoyu-content-design-routing.md'); 'content-svg-diagram'=@('skills/codex-image-workflow/subskills/drawio-skill/SKILL.md','skills/codex-image-workflow/subskills/visual-design-agent/references/baoyu-content-design-routing.md'); 'content-slide-deck'=@('skills/codex-office-cli/subskills/ppt-deck-factory/SKILL.md','skills/codex-image-workflow/subskills/visual-design-agent/references/baoyu-content-design-routing.md'); 'visual-asset'=@('skills/codex-image-workflow/SKILL.md','skills/codex-image-workflow/subskills/visual-format-selection/SKILL.md') }
$artifacts=@('design_brief.md','route_plan.json','assets/','validation/','templates/design-template.json','templates/design-template.md'); if($selectedRoute -eq 'reference-image-reverse-design'){$artifacts+=@('analysis/reference-design.json','analysis/route-improvement-candidate.json')}
$plan = [ordered]@{ schema_version=1; model='visual-design-agent-plan'; agent_id='visual-design-agent'; selected_route=$selectedRoute; goal=$Goal; output_root=$OutputRoot; owners=$routeOwners[$selectedRoute]; required_sources=$routeReferences[$selectedRoute]; required_artifacts=$artifacts; design_system_core=[ordered]@{source='nextlevelbuilder/ui-ux-pro-max-skill';adapter='scripts/Invoke-UiUxProMaxDesignSystem.ps1';required=$true;stage='before route selection';output='design-system/*/MASTER.md plus domain/page override';authority='primary design-system decision layer; selected route owner retains artifact and validation gates'}; design_template_required=$true; template_capture_command='scripts/New-VisualDesignTemplate.ps1'; reference_analysis_required=($selectedRoute -eq 'reference-image-reverse-design'); layout_contract=[ordered]@{layout_policy='content-driven';content_layout_mapping='required for regions, containers, nodes, labels, and connectors';topology_rule='layout follows actual semantic content and relationships';overflow_policy='resize/reflow/regroup/remove after final content placement';template_mutability='source template is provisional until final render QA';format_scope='raster,presentation,drawio,architecture,scientific-figure,infographic,card-series'}; quality_gate=@('hierarchy','alignment','spacing','overlap','connector and arrow attachment where applicable','final-size readability','content-to-layout correspondence','no empty or redundant containers','no clipping or unintended overflow','topology-aware spacing','final-render correction loop','route-specific render and format validation'); next_actions=@('Create a visual design brief','Run UI UX Pro Max design-system core and save MASTER.md plus override','Select the format/editability route from the generated design system','Load only the route-specific owner contract','Select a provisional template and record content-to-layout mappings','Produce and render the selected artifact','Rebalance regions, containers, nodes, connectors, and whitespace based on final content','Run structural and actual-render quality gates','Capture the privacy-safe reusable design template after validation') }
$plan.layout_contract.non_occlusion = 'hard invariant: no important element obscures another element'
if ($Json) { $plan | ConvertTo-Json -Depth 8 } else { $plan }
