#!/usr/bin/env python3
"""Build portable mind-map views and provenance from the canonical vault."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

import yaml


ROOT = Path(__file__).parents[3]
VAULT = ROOT / "knowledge-vault"
MAP_DIR = VAULT / "40-Maps"
HOSTABLE_DIR = VAULT / "assets" / "hostable" / "mindmaps"
LINK = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")


def parse(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}, text
    _, frontmatter, body = text.split("---\n", 2)
    return yaml.safe_load(frontmatter) or {}, body


def mermaid_label(value: str) -> str:
    return re.sub(r"[\[\](){}]", " ", value).strip()


def committed_remote_images() -> list[dict]:
    manifest_dir = VAULT / ".image-hosting" / "manifests"
    latest_by_source = {}
    for path in sorted(manifest_dir.glob("*.json")):
        manifest = json.loads(path.read_text(encoding="utf-8"))
        if manifest.get("status") != "committed":
            continue
        for entry in manifest.get("entries", []):
            latest_by_source[entry["source"]] = {
                "source": entry["source"],
                "remote_url": entry["remote_url"],
                "documents": entry.get("documents", []),
                "sha256": entry.get("sha256"),
                "migration_manifest": path.relative_to(VAULT).as_posix(),
            }
    return [latest_by_source[source] for source in sorted(latest_by_source)]


def main() -> int:
    MAP_DIR.mkdir(parents=True, exist_ok=True)
    HOSTABLE_DIR.mkdir(parents=True, exist_ok=True)
    grouped: dict[str, list[dict]] = defaultdict(list)
    notes = []
    for path in sorted(VAULT.rglob("*.md")):
        if any(part in {".obsidian", "Templates", "40-Maps"} for part in path.parts):
            continue
        if path.name == "Knowledge Index.md":
            continue
        meta, body = parse(path)
        record = {
            "id": meta.get("id", path.stem),
            "name": path.stem,
            "type": meta.get("type", "untyped"),
            "path": path.relative_to(VAULT).as_posix(),
            "links": sorted(set(LINK.findall(body))),
            "learning_audience": meta.get("learning_audience"),
            "user_anki": bool(meta.get("anki_question") and meta.get("anki_answer") and meta.get("learning_audience") in ("user", "both")),
            "codex_learning": bool(meta.get("codex_learning") and meta.get("learning_audience") in ("codex", "both")),
        }
        notes.append(record)
        grouped[record["type"]].append(record)

    outline = ["Codex Knowledge System"]
    mermaid = ["# Codex Knowledge Map", "", "Generated from canonical Markdown notes. Do not edit this file directly.", "", "```mermaid", "mindmap", "  root((Codex Knowledge System))"]
    for note_type in sorted(grouped):
        outline.append(f"\t{note_type}")
        mermaid.append(f"    {mermaid_label(note_type)}")
        for record in sorted(grouped[note_type], key=lambda item: item["name"]):
            labels = []
            if record["codex_learning"]:
                labels.append("Codex")
            if record["user_anki"]:
                labels.append("User Anki")
            marker = f" [{' + '.join(labels)}]" if labels else ""
            mermaid_marker = f" {' + '.join(labels)}" if labels else ""
            outline.append(f"\t\t{record['name']}{marker}")
            mermaid.append(f"      {mermaid_label(record['name'])}{mermaid_marker}")
            for link in record["links"]:
                outline.append(f"\t\t\t-> {link}")
    mermaid.append("```")

    outline_path = MAP_DIR / "Codex Knowledge Map.txt"
    mermaid_path = MAP_DIR / "Codex Knowledge Map.md"
    manifest_path = MAP_DIR / "map-manifest.json"
    outline_path.write_text("\n".join(outline) + "\n", encoding="utf-8")
    mermaid_path.write_text("\n".join(mermaid) + "\n", encoding="utf-8")
    manifest = {
        "schema_version": 1,
        "canonical_source": "Obsidian Markdown notes under knowledge-vault",
        "generated_artifacts": [
            mermaid_path.relative_to(VAULT).as_posix(),
            outline_path.relative_to(VAULT).as_posix(),
        ],
        "mindmaster_working_files": [],
        "hostable_export_directory": HOSTABLE_DIR.relative_to(VAULT).as_posix(),
        "remote_images": committed_remote_images(),
        "notes": notes,
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Generated mind-map views for {len(notes)} notes in {MAP_DIR}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
