#!/usr/bin/env python3
"""Validate linked notes and build Obsidian indexes, graph data, and Anki TSV."""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

import yaml


ROOT = Path(__file__).parents[3]
VAULT = ROOT / "knowledge-vault"
LINK = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")


def parse(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return {}, text
    _, frontmatter, body = text.split("---\n", 2)
    return yaml.safe_load(frontmatter) or {}, body


def main() -> int:
    (VAULT / "00-Home").mkdir(parents=True, exist_ok=True)
    learning_dir = VAULT / "50-Learning"
    learning_dir.mkdir(parents=True, exist_ok=True)
    notes = [
        p for p in VAULT.rglob("*.md")
        if ".obsidian" not in p.parts
        and "Templates" not in p.parts
        and p.name != "Knowledge Index.md"
    ]
    names = {p.stem: p for p in notes}
    names["Knowledge Index"] = VAULT / "00-Home" / "Knowledge Index.md"
    records, missing, user_cards, codex_learning = [], [], [], []
    edges = set()
    seen_ids = {}
    for path in notes:
        meta, body = parse(path)
        note_id = meta.get("id")
        if note_id:
            if note_id in seen_ids:
                missing.append(f"duplicate id {note_id}: {path} and {seen_ids[note_id]}")
            seen_ids[note_id] = path
        links = sorted(set(LINK.findall(body)))
        for target in links:
            if target not in names:
                missing.append(f"missing link {target} from {path.relative_to(VAULT)}")
            else:
                edges.add((path.stem, target))
        audience = meta.get("learning_audience")
        question, answer = meta.get("anki_question"), meta.get("anki_answer")
        codex_summary = meta.get("codex_learning")
        if audience not in (None, "codex", "user", "both"):
            missing.append(f"invalid learning_audience {audience}: {path.relative_to(VAULT)}")
        if bool(question) != bool(answer):
            missing.append(f"incomplete user Anki fields: {path.relative_to(VAULT)}")
        if question and audience not in ("user", "both"):
            missing.append(f"user Anki fields require learning_audience user or both: {path.relative_to(VAULT)}")
        if audience in ("user", "both") and not (question and answer):
            missing.append(f"user learning requires anki_question and anki_answer: {path.relative_to(VAULT)}")
        if codex_summary and audience not in ("codex", "both"):
            missing.append(f"codex_learning requires learning_audience codex or both: {path.relative_to(VAULT)}")
        if audience in ("codex", "both") and not codex_summary:
            missing.append(f"Codex learning requires codex_learning summary: {path.relative_to(VAULT)}")
        record = {"name": path.stem, "path": str(path.relative_to(VAULT)), "type": meta.get("type", "untyped"), "status": meta.get("status", "unknown"), "learning_audience": audience, "links": links}
        records.append(record)
        if question and answer and audience in ("user", "both"):
            deck = str(meta.get("anki_deck", "Codex Knowledge"))
            tags = f"user-learning codex::{note_id or path.stem}"
            user_cards.append((str(question), str(answer), deck, tags))
        if codex_summary and audience in ("codex", "both"):
            codex_learning.append({
                "id": note_id or path.stem,
                "name": path.stem,
                "path": str(path.relative_to(VAULT)),
                "summary": str(codex_summary),
                "source": meta.get("source"),
                "verified": bool(meta.get("verified")),
            })

    index = ["# Knowledge Index", "", "Generated by `build_knowledge.py`.", ""]
    for record in sorted(records, key=lambda item: (item["type"], item["name"])):
        index.append(f"- `{record['type']}` [[{record['name']}]] ({len(record['links'])} links)")
    (VAULT / "00-Home" / "Knowledge Index.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    (VAULT / "00-Home" / "graph.json").write_text(json.dumps({"nodes": records, "edges": sorted(edges)}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    with (learning_dir / "user-anki-import.tsv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t")
        writer.writerow(["Front", "Back", "Deck", "Tags"])
        writer.writerows(user_cards)
    (learning_dir / "codex-learning.json").write_text(
        json.dumps({"schema_version": 1, "audience": "codex", "entries": sorted(codex_learning, key=lambda item: item["id"])}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    legacy = VAULT / "50-Cards" / "anki-import.tsv"
    if legacy.exists():
        legacy.unlink()
    if missing:
        print("\n".join(missing))
        return 1
    print(f"Validated {len(notes)} notes, {len(edges)} links, {len(codex_learning)} Codex learning entries, and {len(user_cards)} user Anki cards.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
